In [191]:
import numpy as np

Exercice 1 : Création et manipulation de réseaux
Créez un tableau NumPy 1D contenant des nombres de 0 à 9.

In [192]:
tableau1 = np.arange(10)
print(tableau1)

[0 1 2 3 4 5 6 7 8 9]


Exercice 2 : Conversion de type et opérations sur l’array
Convertissez la liste `[3.14, 2.17, 0, 1, 2]` en tableau NumPy et convertissez son type de données en entier.

In [193]:
liste_depart = [3.14, 2.17, 0, 1, 2]
tableau2 = np.array(liste_depart).astype(int)
print(tableau2)

[3 2 0 1 2]


Exercice 3 : Travailler avec des réseaux multidimensionnels
Créez un tableau NumPy 3x3 avec des valeurs allant de 1 à 9.

In [194]:
tableau3 = np.arange(1, 10).reshape(3, 3)
print(tableau3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercice 4 : Créer un tableau multidimensionnel avec des nombres aléatoires
Créez un tableau NumPy 2D de formes (4, 5) remplies de nombres aléatoires.

In [195]:
tableau4 = np.random.rand(4, 5)
print(tableau4)

[[0.21459491 0.77366725 0.31578138 0.60256304 0.32667785]
 [0.44293718 0.10310263 0.44647315 0.91297897 0.60544031]
 [0.01222523 0.70420734 0.71994701 0.43347285 0.19507125]
 [0.27320941 0.3835134  0.25970369 0.11664413 0.18973738]]


 Exercise 5 : Indexing Arrays
Sélectionner la deuxième ligne du tableau 2D donné.

In [196]:
matrice = np.array([[21, 22, 23, 22, 22],
                    [20, 21, 22, 23, 24],
                    [21, 22, 23, 22, 22]])

deuxieme_ligne = matrice[1]

print(deuxieme_ligne)

[20 21 22 23 24]


Exercice 6 : Inverser les éléments
Inversez l’ordre des éléments dans un tableau NumPy 1D donné.

In [197]:
tableau6 = np.arange(10)
tableau_inverse = tableau6[::-1]
print(tableau_inverse)

[9 8 7 6 5 4 3 2 1 0]


 Exercice 7 : Matrice d’identité
 Créez une matrice d’identité 4x4 en utilisant NumPy.

In [198]:
matrice_identite = np.eye(4)
print(matrice_identite)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Exercice 8 : Fonctions agrégées simples
Trouvez la somme et la moyenne d’un tableau 1D donné (de 0 à 9).

In [199]:
tableau8 = np.arange(10)
somme = tableau8.sum()
moyenne = tableau8.mean()

print(f"Sum: {somme}, Average: {moyenne}")

Sum: 45, Average: 4.5


Exercice 9 : Créer un tableau et changer sa structure
Créer un tableau NumPy avec des éléments allant de 1 à 20, puis remodelez-le en une matrice 4x5.

In [200]:
tableau9 = np.arange(1, 21).reshape(4, 5)
print(tableau9)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Exercice 10 : Conditional Selection of Values
Extraire tous les nombres impairs d’un tableau NumPy donné (de 1 à 9).

In [201]:
tableau10 = np.arange(1, 10)
nombres_impairs = tableau10[tableau10 % 2 != 0]
print(nombres_impairs)

[1 3 5 7 9]
